using System.Text;


public static class GlobalStatic
{
    public static string applicationName = "DirtSWS";
    public static string sessionCookieName = "DirtSWSSessionCookie";
    public static string antiForgeryCookieName = "DirtSWSAntiForgeryCookie";
    public static string webSite = "https://github.com/tezoatlipoca/DirtSWS";

    public static string? staticAboutPage = null;

    // generates everything from the footer to the closing html tag
    // including the closing body tag
    public static void GeneratePageFooter(StringBuilder sb)
    {
        sb.AppendLine("<footer>");
        sb.AppendLine($"<div class=\"byline\">Generated by {GlobalStatic.applicationName} instance {GlobalConfig.Hostname} at {DateTime.Now}</div>");
        sb.AppendLine($"<div class=\"byline\">Build # {GlobalConfig.bldVersion}. For more information, visit <a href=\"{GlobalStatic.webSite}\">{GlobalStatic.webSite}</a></div>");
        sb.AppendLine("</footer>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
    }

    // generates everything up to and including the opening body tag
    public static void GenerateHTMLHead(StringBuilder sb, string title = "")
    {
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html>");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        if(GlobalConfig.sitecss != null)
        {
            //sb.AppendLine($"<link rel=\"stylesheet\" type=\"text/css\" href=\"/{GlobalConfig.sitecss}\">");
            sb.AppendLine("<style>");
            sb.AppendLine(GlobalConfig.sitecss);
            sb.AppendLine("</style>");
        }
        if(GlobalConfig.sitepng != null)
        {
            sb.AppendLine($"<link rel=\"icon\" href=\"{GlobalConfig.sitepng}\" type=\"image/png\">");
        }
        sb.AppendLine($"<title>{GlobalConfig.Hostname} - {title}</title>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body >");
        sb.AppendLine($"<h1>{title}</h1>");
        sb.AppendLine("<p><a href=\"/\">Home</a></p>");
        sb.AppendLine("<span class=\"results\" style=\"color: red;\"></span>");
    }

    public static async Task GenerateUnAuthPage(StringBuilder sb, string msg)
    {
        DBg.d(LogLevel.Trace, "GenerateUnAuthPage");
        // get all the lists

        GenerateHTMLHead(sb, "Unauthorized");

        
        sb.AppendLine($"<p style=\"color: red;\">{msg}</p>");
        sb.AppendLine("<p>Go back to <a href=\"/login\">the login page?</a></p>");
        GeneratePageFooter(sb);
    }



    public static async Task<StringBuilder> Generate404Page(string requestPath, string userInfo)
    {
        DBg.d(LogLevel.Trace, "Generate404Page");
        // get all the lists
        StringBuilder sb = new StringBuilder();
        GenerateHTMLHead(sb, "404 Not Found");

        //sb.AppendLine($"<h1 class=\"indextitle\">404</h1>");
        sb.AppendLine($"<p style=\"color: red;\">Page not found</p>");
        sb.AppendLine($"<p>Requested path: {requestPath}</p>");
        sb.AppendLine($"<p>You are: {userInfo}</p>");
        sb.AppendLine($"<p>Go back to <a href=\"{GlobalConfig.index}\">the index page?</a></p>");
        GeneratePageFooter(sb);
        return sb;
    }
 public static void GenerateAboutPage()
    {
        DBg.d(LogLevel.Trace, "GenerateAboutPage");
        
        StringBuilder sb = new StringBuilder();
        GlobalStatic.GenerateHTMLHead(sb, "About DirtSWS");
        sb.AppendLine("<p><code>DirtSWS</code> is a simple, single binary, self-hosted static file webserver that provides simple file management.</p>");
        sb.AppendLine("<p>To upload files, go to:</p>");
        sb.AppendLine($"<pre>{GlobalConfig.Hostname}/files</pre>");
        sb.AppendLine("<p>.. using the password specified when you launched <code>DirtSWS</code>.</p>");
        sb.AppendLine("<p>Files uploaded there are stored in the configured <code>wwwroot</code> configured when DirtSWS was launched and they're available at:</p>");
        sb.AppendLine($"<pre>{GlobalConfig.Hostname}/&lt;filename&gt;</pre>");
        sb.AppendLine("<p>Site icon and \"built in\" page stylesheet can also be specified at the command line when launched.</p>");
        sb.AppendLine($"<p>Apart from that, its all static files of your own design.</p>");
        
        
        sb.AppendLine($"<p>This <code>DirtSWS</code> instance is provided by {GlobalConfig.siteInformation}</p>");
        GlobalStatic.GeneratePageFooter(sb);
        staticAboutPage = sb.ToString();
    }

}

