using System.Text;


public static class GlobalStatic
{
    public static string applicationName = "DirtSWS";
    public static string sessionCookieName = "DirtSWSSessionCookie";
    public static string antiForgeryCookieName = "DirtSWSAntiForgeryCookie";
    public static string webSite = "https://github.com/tezoatlipoca/DirtSWS";

    public static string? staticAboutPage = null;

    // generates everything from the footer to the closing html tag
    // including the closing body tag
    public static void GeneratePageFooter(StringBuilder sb)
    {
        sb.AppendLine("<footer>");
        sb.AppendLine($"<div class=\"byline\">Generated by {GlobalStatic.applicationName} instance {GlobalConfig.Hostname} at {DateTime.Now}</div>");
        sb.AppendLine($"<div class=\"byline\">Build # {GlobalConfig.bldVersion}. For more information, visit <a href=\"{GlobalStatic.webSite}\">{GlobalStatic.webSite}</a></div>");
        sb.AppendLine("</footer>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
    }

    // generates everything up to and including the opening body tag
    public static void GenerateHTMLHead(StringBuilder sb, string title = "")
    {
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html>");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        if(GlobalConfig.sitecss != null)
        {
            //sb.AppendLine($"<link rel=\"stylesheet\" type=\"text/css\" href=\"/{GlobalConfig.sitecss}\">");
            sb.AppendLine("<style>");
            sb.AppendLine(GlobalConfig.sitecss);
            sb.AppendLine("</style>");
        }
        if(GlobalConfig.sitepng != null)
        {
            sb.AppendLine($"<link rel=\"icon\" href=\"{GlobalConfig.sitepng}\" type=\"image/png\">");
        }
        sb.AppendLine($"<title>{GlobalConfig.Hostname} - {title}</title>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body >");
        sb.AppendLine($"<h1>{title}</h1>");
        sb.AppendLine("<p><a href=\"/\">Home</a> | <a href=\"/files\">Files</a> | <a href=\"/about\">About</a></p>");
        sb.AppendLine("<span class=\"results\" style=\"color: red;\"></span>");
    }

    public static StringBuilder GenerateUnAuthPage(StringBuilder sb, string msg)
    {
        DBg.d(LogLevel.Trace, "GenerateUnAuthPage");
        // get all the lists

        GenerateHTMLHead(sb, "Unauthorized");


        sb.AppendLine($"<p style=\"color: red;\">{msg}</p>");
        sb.AppendLine("<p>Go back to <a href=\"/login\">the login page?</a></p>");
        GeneratePageFooter(sb);
        return sb;
    }



    public static StringBuilder Generate404Page(string requestPath, string userInfo)
    {
        DBg.d(LogLevel.Trace, "Generate404Page");
        // get all the lists
        StringBuilder sb = new StringBuilder();
        GenerateHTMLHead(sb, "404 Not Found");

        //sb.AppendLine($"<h1 class=\"indextitle\">404</h1>");
        sb.AppendLine($"<p style=\"color: red;\">Page not found: {requestPath}</p>");
        
        sb.AppendLine($"<p>You are: {userInfo}</p>");
        sb.AppendLine($"<p>Go back to <a href=\"{GlobalConfig.index}\">the index page?</a></p>");
        GeneratePageFooter(sb);
        return sb;
    }
 public static void GenerateAboutPage()
    {
        DBg.d(LogLevel.Trace, "GenerateAboutPage");
        
        StringBuilder sb = new StringBuilder();
        GlobalStatic.GenerateHTMLHead(sb, "About DirtSWS");
        sb.AppendLine("<p><code>DirtSWS</code> is a simple, single binary, self-hosted static file webserver that provides simple file management.</p>");
        sb.AppendLine("<p>To upload files, go to:</p>");
        sb.AppendLine($"<pre>{GlobalConfig.Hostname}/files</pre>");
        sb.AppendLine("<p>.. using the password specified when you launched <code>DirtSWS</code>.</p>");
        sb.AppendLine("<p>Files uploaded there are stored in the configured <code>wwwroot</code> configured when DirtSWS was launched and they're available at:</p>");
        sb.AppendLine($"<pre>{GlobalConfig.Hostname}/&lt;filename&gt;</pre>");
        sb.AppendLine("<p>Site icon and \"built in\" page stylesheet can also be specified at the command line when launched.</p>");
        sb.AppendLine($"<p>Apart from that, its all static files of your own design.</p>");
        
        
        sb.AppendLine($"<p>This <code>DirtSWS</code> instance is provided by {GlobalConfig.siteInformation}</p>");
        GlobalStatic.GeneratePageFooter(sb);
        staticAboutPage = sb.ToString();
    }

    public static string uploadJS = @"
    function uploadFiles() {
        // Try directory input first, fallback to files input
        var fileInputDir = document.getElementById('fileInputDir');
        var fileInputFiles = document.getElementById('fileInputFiles');
        var files = fileInputDir.files.length > 0 ? fileInputDir.files : fileInputFiles.files;
        var totalFiles = files.length;
        var progressBar = document.getElementById('progressBar');
        var progressLabel = document.getElementById('progressLabel');
        var statusDiv = document.getElementById('status');

        // Get the antiforgery token from the form
        var tokenInput = document.getElementById('antiforgeryToken');
        var token = tokenInput ? tokenInput.value : '';

        if (totalFiles === 0) {
            statusDiv.innerText = 'No files selected.';
            return;
        }

        let currentFile = 0;

 

        function uploadNextFile() {
            if (currentFile >= totalFiles) {
                statusDiv.innerText = 'All files uploaded.';
                progressBar.value = 0;
                progressLabel.innerText = '';
                window.location.href = '/files';
                return;
            }

            var formData = new FormData();
            formData.append('file', files[currentFile]);
            formData.append('__RequestVerificationToken', token);

            // Only append webkitRelativePath if present
            if (files[currentFile].webkitRelativePath !== undefined && files[currentFile].webkitRelativePath !== '') {
                formData.append('webkitRelativePath', files[currentFile].webkitRelativePath);
            }

            var xhr = new XMLHttpRequest();
            xhr.open('POST', '/fileuploadxfer', true);

            xhr.upload.onprogress = function (e) {
                if (e.lengthComputable) {
                    var percent = (e.loaded / e.total) * 100;
                    progressBar.value = percent;
                    progressLabel.innerText = 'Uploading ' + files[currentFile].name + ' (' + (currentFile + 1) + ' of ' + totalFiles + ')';
                }
            };

            xhr.onload = function () {
                statusDiv.innerText = xhr.responseText;
                progressBar.value = 0;
                if (xhr.status === 200) {
                    currentFile++;
                    uploadNextFile();
                } else {
                    progressLabel.innerText = '';
                    // Provide more explanation for possible server errors
                    let errorMsg = 'Upload failed for ' + files[currentFile].name + '. ';
                    if (xhr.status === 413) {
                        errorMsg += 'The file is too large for the server to accept (HTTP 413: Content Too Large).';
                    } else if (xhr.status >= 500) {
                        errorMsg += 'A server error occurred (HTTP ' + xhr.status + ').';
                    } else if (xhr.status >= 400) {
                        errorMsg += 'A client or server error occurred (HTTP ' + xhr.status + ').';
                    } else {
                        errorMsg += 'Unknown error; check server output/log.';
                    }
                    statusDiv.innerText = errorMsg;
                    statusDiv.style.color = 'red';
                }
            };

            xhr.onerror = function () {
                progressLabel.innerText = '';
                statusDiv.innerText = 'Upload failed for ' + files[currentFile].name;
                statusDiv.style.color = 'red';
            };

            xhr.send(formData);
        }
           uploadNextFile();
    }";
}

